shop-template-buy:
  material: CHEST_MINECART
  display-name: <#00aaff><bold>%owner%
  lore:
    - '<white>Buy:</white> <red>%buy-price%</red>'
    - '<white>Unit Buy:</white> <red>%buy-price-unit%</red>'
    - '<white>Quantity:</white> <aqua>%quantity%</aqua> <gray>|</gray> <white>Stock:</white> <aqua>%stock%</aqua>'
    - '<white>Remaining Capacity:</white> <light_purple>%capacity%'
    - '<white>Distance:</white> <yellow>%distance%</yellow>'
    - '<white>Location:</white> <gold>%x%, %y%, %z%</gold> <dark_grey>(%world%)'
shop-template-sell:
  material: HOPPER_MINECART
  display-name: <#00aaff><bold>%owner%
  lore:
    - '<white>Sell:</white> <green>%sell-price%</green>'
    - '<white>Unit Sell:</white> <green>%sell-price-unit%</green>'
    - '<white>Quantity:</white> <aqua>%quantity%</aqua> <gray>|</gray> <white>Stock:</white> <aqua>%stock%</aqua>'
    - '<white>Remaining Capacity:</white> <light_purple>%capacity%'
    - '<white>Distance:</white> <yellow>%distance%</yellow>'
    - '<white>Location:</white> <gold>%x%, %y%, %z%</gold> <dark_grey>(%world%)'
shop-template-both:
  material: ENDER_CHEST
  display-name: <#00aaff><bold>%owner%
  lore:
    - '<white>Buy:</white> <red>%buy-price%</red> <gray>|</gray> <white>Sell:</white> <green>%sell-price%</green>'
    - '<white>Unit Buy:</white> <red>%buy-price-unit%</red> <gray>|</gray> <white>Unit Sell:</white> <green>%sell-price-unit%</green>'
    - '<white>Quantity:</white> <aqua>%quantity%</aqua> <gray>|</gray> <white>Stock:</white> <aqua>%stock%</aqua>'
    - '<white>Remaining Capacity:</white> <light_purple>%capacity%'
    - '<white>Distance:</white> <yellow>%distance%</yellow>'
    - '<white>Location:</white> <gold>%x%, %y%, %z%</gold> <dark_grey>(%world%)'
shop-icon-click-command: 'compass start <x> <y> <z>'
shop-preview-default-visibility: true
shop-preview-scale: 0.5